# Generated by Django 2.1.7 on 2019-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20190320_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='dietary_specs',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_attending',
        ),
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='song',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
